#!/bin/bash

# Quick verification script for symbol search endpoint
# Usage: ./scripts/verify_search_endpoint.sh

BASE_URL="http://127.0.0.1:8000"

echo "=== Symbol Search Endpoint Verification ==="
echo ""
echo "Prerequisites:"
echo "1. Server must be running: uvicorn app.main:app --reload"
echo "2. You need a registered user and auth token"
echo ""
echo "To test manually:"
echo ""
echo "# 1. Register a user (if not already done):"
echo "curl -X POST \"$BASE_URL/auth/register\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"test@example.com\",\"password\":\"testpass123\"}'"
echo ""
echo "# 2. Login to get token:"
echo "curl -X POST \"$BASE_URL/auth/login\" \\"
echo "  -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "  -d 'username=test@example.com&password=testpass123'"
echo ""
echo "# 3. Copy the access_token from the response above, then:"
echo "TOKEN=\"your_token_here\""
echo ""
echo "# 4. Ingest a symbol (optional, if not already done):"
echo "curl -X POST \"$BASE_URL/stocks/AAPL/ingest?start=2023-01-01&end=2023-01-10\" \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""
echo "# 5. Test the search endpoint:"
echo "curl -X GET \"$BASE_URL/stocks/search?q=AA&limit=5\" \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""
echo "# Or visit the interactive docs:"
echo "open $BASE_URL/docs"
echo ""
